# Generated by Django 5.0.6 on 2024-08-10 20:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountmodel",
            name="type",
        ),
    ]
