# Generated by Django 5.0.6 on 2024-08-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_accountmodel_iam_provider_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountmodel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
