# Generated by Django 5.0.6 on 2024-08-13 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_alter_accountmodel_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountmodel",
            name="temporal_password",
        ),
    ]
